# Generated by Django 4.2.3 on 2023-07-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_category_category'),
    ]

    operations = [
    migrations.AlterModelOptions(
        name='Category',
        options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
    ),
    migrations.AlterModelOptions(
        name='Items',
        options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
    ),
    migrations.AlterModelOptions(
        name='Listing',
        options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
    ),
]
