# Generated by Django 4.2.3 on 2023-07-28 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_category_options_alter_items_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
