# Generated by Django 4.2.3 on 2023-07-31 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comments_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='owner_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
