# Generated by Django 4.2.3 on 2023-07-31 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_items_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='owner_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
